const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('fs'),path=require('path');
const base=process.env.GIS_TEST_URL||'http://127.0.0.1:8765/SideEconomyLab/';
fs.mkdirSync('/tmp/decision-browser',{recursive:true});
(async()=>{
 const browser=await chromium.launch({headless:true,...(process.env.WORKBENCH_CHROMIUM?{executablePath:process.env.WORKBENCH_CHROMIUM}:{})});
 const page=await browser.newPage({viewport:{width:1600,height:1000}}),errors=[],privateWrites=[],authenticated=[];
  await page.addInitScript(()=>{if(!location.hash)history.replaceState(null,'',location.pathname+'#evaluate');});
 page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(r.method()!=='GET')privateWrites.push(r.method());if(/apis\.data\.go\.kr|reb\.or\.kr/.test(r.url()))authenticated.push('server-only-domain-request');});
 for(const [url,file] of [['https://unpkg.com/leaflet@1.9.4/dist/leaflet.js','leaflet/dist/leaflet.js'],['https://unpkg.com/leaflet@1.9.4/dist/leaflet.css','leaflet/dist/leaflet.css'],['https://cdnjs.cloudflare.com/ajax/libs/proj4js/2.11.0/proj4.js','proj4/dist/proj4.js']])await page.route(url,r=>r.fulfill({path:require.resolve(file)}));
 await page.route('https://*.tile.openstreetmap.org/**',r=>r.abort());
 await page.goto(base+'#evaluate');await page.waitForFunction(()=>document.querySelectorAll('.di-play').length===4);
 assert.ok(await page.locator('#di-variant').isVisible());assert.equal(await page.locator('#filter-panel').evaluate(e=>e.open),false);assert.ok((await page.locator('#decision-panel').innerText()).startsWith('선택 사업안 판단'));
 const rankBox=await page.locator('.top-item').nth(4).boundingBox();assert.ok(rankBox.y+rankBox.height<1000,'ranked locations visible without opening long filters');
 const mapBox=await page.locator('#map').boundingBox();assert.ok(mapBox.width>800);
 await page.selectOption('#candidate','vending');await page.selectOption('#di-variant','VEND-BEVERAGE');await page.waitForFunction(()=>document.querySelector('.di-play')?.dataset.variant==='VEND-BEVERAGE');
 assert.equal(await page.locator('.di-selected .di-status-badge').getAttribute('data-status'),'CHECK');assert.equal(await page.locator('.di-alternatives .di-play').count(),3);assert.ok(await page.locator('.di-alternatives .di-play').evaluateAll(cards=>new Set(cards.map(c=>c.dataset.family)).size>=2));
 const selectedArea=await page.evaluate(()=>state.selectedArea.trdar_cd),alternative=await page.locator('.di-alternatives .di-play').first().getAttribute('data-variant');await page.locator('.di-alternatives [data-play]').first().click();assert.equal(await page.locator('.di-selected .di-play').getAttribute('data-variant'),alternative);assert.equal(await page.evaluate(()=>state.selectedArea.trdar_cd),selectedArea,'cross-family selection preserves location');await page.selectOption('#candidate','vending');await page.selectOption('#di-variant','VEND-BEVERAGE');
 assert.equal(await page.locator('#di-variant option').count(),4,'source-backed snack and amenity variants');
 const overview=await page.locator('.di-play').first().innerText();for(const term of ['초기 현금','월 고정 공간비','손익분기','필요 포획률','낮음','다음 하나','계약 모델의 기획 공간비','낮음','계획용 환산','관측성 낮음 — 경쟁 부재를 의미하지 않음'])assert.ok(overview.includes(term),term);
 await page.locator('#decision-panel').evaluate(e=>e.parentElement.scrollTop=0);await page.screenshot({path:'/tmp/decision-browser/myeongdong-vending.png'});
 await page.selectOption('#candidate','booth');await page.selectOption('#di-variant','BOOTH-SING');await page.evaluate(()=>selectArea(state.data.areas.find(a=>a.trdar_cd==='3120189'),{openSheet:false}));await page.waitForFunction(()=>document.querySelector('.di-play')?.dataset.variant==='BOOTH-SING');assert.ok((await page.locator('.di-play').first().innerText()).includes('가동'));await page.locator('#intelligence').evaluate(e=>e.scrollTop=0);await page.screenshot({path:'/tmp/decision-browser/gangnam-singing-booth.png'});
 await page.selectOption('#candidate','vending');await page.selectOption('#di-variant','VEND-BEVERAGE');await page.evaluate(()=>selectArea(state.data.areas.find(a=>a.trdar_cd==='3001492'),{openSheet:false}));
 const details=page.locator('.di-detail').filter({hasText:'사이트 비용 추정 · 실제 견적과 구별'});await details.locator('summary').first().click();await page.fill('#di-rent','5000000');await page.click('#di-save-site');await page.locator('.di-detail').filter({hasText:'투자·손익분기 자세히'}).locator('summary').first().click();await page.fill('#di-volume','300');await page.click('#di-save-volume');assert.ok((await page.locator('.di-play').first().innerText()).includes('불리한 조건'));await page.locator('.di-detail').filter({hasText:'투자·손익분기 자세히'}).locator('summary').first().click();assert.ok((await page.locator('#decision-panel').innerText()).includes('검토 물량에서 경제성 조건 미충족'));
 await page.screenshot({path:'/tmp/decision-browser/unfavorable-site.png'});
 await details.locator('summary').first().click();await page.fill('#di-blockers','PRIVATE host prohibits installation');await page.click('#di-save-site');assert.equal(await page.locator('.di-play .di-status-badge').first().getAttribute('data-status'),'BLOCKED');await details.locator('summary').first().click();await page.fill('#di-blockers','');await page.click('#di-save-site');assert.equal(await page.locator('.di-play .di-status-badge').first().getAttribute('data-status'),'WEAK');
 // Hover-first: mouse leave, Escape and map background dismiss, including mobile tap.
 await page.locator('#intelligence').evaluate(e=>e.scrollTop=0);await page.evaluate(()=>state.adapter.focus(toLatLng(state.selectedArea)));await page.waitForTimeout(100);await page.evaluate(()=>{for(const el of document.querySelectorAll('.poi-marker')){const r=el.getBoundingClientRect(),hit=document.elementFromPoint(r.x+r.width/2,r.y+r.height/2);if(hit===el){el.dataset.testExposed='true';break;}}});const marker=page.locator('[data-test-exposed=true]');await marker.hover();await page.locator('.leaflet-tooltip').waitFor();await page.mouse.move(mapBox.x+5,mapBox.y+5);await page.waitForFunction(()=>document.querySelectorAll('.leaflet-tooltip').length===0);assert.equal(await page.locator('.leaflet-tooltip').count(),0);await marker.click();await page.locator('.leaflet-tooltip').waitFor();await page.keyboard.press('Escape');await page.waitForFunction(()=>document.querySelectorAll('.leaflet-tooltip').length===0);assert.equal(await page.locator('.leaflet-tooltip').count(),0);
 await page.locator('#filter-panel').evaluate(e=>e.open=true);for(const mode of ['supply','quadrant','demand']){await page.selectOption('#map-mode',mode);const legend=await page.locator('#map-legend').innerText();for(const text of ['직접 경쟁형','대체형','문맥','개인/실제 후보지','선택 상권'])assert.ok(legend.includes(text));}
 // Explicit map creation and browser-only quick terms.
 await page.click('#di-map-create');await page.mouse.click(mapBox.x+mapBox.width*.45,mapBox.y+mapBox.height*.4);await page.waitForFunction(()=>document.querySelector('#di-location').value!=='');
 assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('SideEconomyLab.business-workbench.v1')).sites.length),1);assert.equal(await page.locator('.site-marker').count(),1);
 await page.locator('.di-detail').filter({hasText:'사이트 비용 추정 · 실제 견적과 구별'}).locator('summary').first().click();
 for(const [id,value] of [['di-area','6'],['di-floor','2'],['di-rent','900000'],['di-quick-deposit','9000000'],['di-quick-management','100000'],['di-quick-key_money','0'],['di-quick-host_share','.1']])await page.fill('#'+id,value);
 await page.click('#di-save-site');assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('SideEconomyLab.business-workbench.v1')).sites[0].rent.value),900000);assert.ok((await page.locator('.di-selected').innerText()).includes('대상 사이트 실제 입력 조건'));
 const privateSite=await page.inputValue('#di-location'),privateArea=await page.evaluate(()=>state.selectedArea.trdar_cd);await page.locator('.di-alternatives [data-play]').first().click();assert.equal(await page.inputValue('#di-location'),privateSite);assert.equal(await page.evaluate(()=>state.selectedArea.trdar_cd),privateArea);assert.ok(!(await page.locator('.di-selected').innerText()).includes('대상 사이트 실제 입력 조건'),'host quote cannot silently transfer to another variant');
 await page.selectOption('#candidate','booth');await page.selectOption('#di-variant','BOOTH-SING');await page.selectOption('#di-location',privateSite);assert.ok(!(await page.locator('.di-selected').innerText()).includes('대상 사이트 실제 입력 조건'),'host quote stored in legacy workspace must not become a full-lease quote');
 await page.reload();await page.waitForFunction(()=>document.querySelectorAll('.di-play').length===4);assert.equal(await page.locator('#di-location option').count(),2);
 // Complete private backup/import and owner override preserve public status.
 await page.selectOption('#candidate','vending');await page.selectOption('#di-variant','VEND-BEVERAGE');await page.selectOption('#di-location',{index:1});
 await page.locator('.di-detail').filter({hasText:'소유자 판단 · 관측 결과 · 개인 백업'}).locator('summary').first().click();await page.selectOption('#di-judgment','STRONG');await page.fill('#di-reason','PRIVATE judgement');await page.fill('#di-change','PRIVATE evidence');const before=await page.locator('.di-play .di-status-badge').first().getAttribute('data-status');await page.click('#di-save-judgment');assert.equal(await page.locator('.di-play .di-status-badge').first().getAttribute('data-status'),before);assert.ok((await page.locator('.di-play').first().innerText()).includes('개인 판단 긍정'));
 await page.locator('.di-detail').filter({hasText:'소유자 판단 · 관측 결과 · 개인 백업'}).locator('summary').first().click();const downloadEvent=page.waitForEvent('download');await page.click('#di-export');const file=await (await downloadEvent).path();const backup=JSON.parse(fs.readFileSync(file));assert.equal(backup.workbench.sites[0].rent.value,900000);assert.ok(Object.keys(backup.decision.envelopes).length>0);
 await page.locator('#di-import').setInputFiles({name:'backup.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(backup))});await page.waitForFunction(()=>document.querySelector('#di-status').textContent.includes('복원 완료'));
 // Invalid private restore must preserve both keys.
 const saved=await page.evaluate(()=>[localStorage.getItem('SideEconomyLab.decision-intelligence.v1'),localStorage.getItem('SideEconomyLab.business-workbench.v1')]);await page.locator('.di-detail').filter({hasText:'소유자 판단 · 관측 결과 · 개인 백업'}).locator('summary').first().click();await page.locator('#di-import').setInputFiles({name:'invalid.json',mimeType:'application/json',buffer:Buffer.from('{"schema_version":999}')});await page.waitForFunction(()=>document.querySelector('#di-status').textContent.includes('복원 실패'));assert.deepEqual(await page.evaluate(()=>[localStorage.getItem('SideEconomyLab.decision-intelligence.v1'),localStorage.getItem('SideEconomyLab.business-workbench.v1')]),saved);
 // Missing public rent remains unknown on cards, never management-only or zero break-even.
 await page.route('**/data/decision-evidence.json',r=>r.fulfill({status:404,body:''}));await page.route('**/data/real-estate-context.json',r=>r.fulfill({status:404,body:''}));await page.reload();await page.waitForFunction(()=>document.querySelectorAll('.di-play').length===4);await page.selectOption('#candidate','booth');await page.selectOption('#di-variant','BOOTH-CALL');await page.selectOption('#di-location','');await page.locator('.di-detail').filter({hasText:'사이트 비용 추정 · 실제 견적과 구별'}).locator('summary').first().click();await page.selectOption('#di-site-model','FULL_LEASE');await page.click('#di-save-site');const unknownCard=await page.locator('.di-play').first().innerText();assert.ok(unknownCard.includes('미확인 – 미확인'));assert.ok(unknownCard.includes('미확인건/일'));await page.unroute('**/data/decision-evidence.json');await page.unroute('**/data/real-estate-context.json');
 await page.setViewportSize({width:390,height:844});await page.reload();await page.waitForFunction(()=>document.querySelectorAll('.di-play').length===4);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.ok(await page.locator('#di-variant').isVisible());assert.ok(await page.locator('#decision-panel').isVisible(),'evaluation opens the selected panel on mobile');await page.click('.mobile-tabs [data-sheet="decision"]');assert.ok(!await page.locator('#decision-panel').isVisible());await page.click('.mobile-tabs [data-sheet="decision"]');assert.ok(await page.locator('#decision-panel').isVisible());await page.screenshot({path:'/tmp/decision-browser/mobile-decision.png'});
 await page.click('#intelligence [data-sheet="close"]');await page.click('.mobile-tabs [data-sheet="filters"]');await page.locator('#filter-panel').evaluate(e=>e.open=true);await page.selectOption('#map-mode','quadrant');assert.ok((await page.locator('#map-legend').innerText()).includes('A 고수요'));await page.click('#navigator [data-sheet="close"]');
 // Synthetic stronger-evidence UI fixture: never saved as public source data.
 await page.setViewportSize({width:1600,height:1000});
 const fixture=JSON.parse(fs.readFileSync('docs/data/decision-evidence.json'));fixture.stores=[];fixture.retrieved_at=new Date().toISOString();
 const places=JSON.parse(fs.readFileSync('docs/data/kakao-poi-layer.json'));for(const family of Object.values(places.candidates))for(const a of family.areas)a.pois=[];
 await page.route('**/data/decision-evidence.json',r=>r.fulfill({json:fixture}));await page.route('**/data/kakao-poi-layer.json',r=>r.fulfill({json:places}));
 await page.evaluate(()=>{localStorage.removeItem('SideEconomyLab.decision-intelligence.v1');localStorage.removeItem('SideEconomyLab.business-workbench.v1');});await page.reload();await page.waitForFunction(()=>document.querySelectorAll('.di-play').length===4);
 await page.selectOption('#candidate','photo');await page.selectOption('#di-variant','DOCUMENT-PRINT');await page.evaluate(()=>selectArea(state.data.areas.find(a=>a.trdar_cd==='3001492'),{openSheet:false}));
 const terms=page.locator('.di-detail').filter({hasText:'사이트 비용 추정 · 실제 견적과 구별'});await terms.locator('summary').first().click();assert.ok((await terms.innerText()).includes('MARKET RENT BASELINE'));await page.selectOption('#di-site-model','FULL_LEASE');await page.fill('#di-rent','100000');await page.fill('#di-flow','100000');await page.selectOption('#di-owner','true');await page.click('#di-save-site');assert.equal(await page.locator('.di-selected .di-status-badge').getAttribute('data-status'),'PROMISING');assert.ok((await page.locator('.di-selected').innerText()).includes('양호'));assert.equal(await page.locator('.di-selected .di-play').getAttribute('data-capture-evidence'),'USER_INPUT');assert.ok((await page.locator('.di-selected').innerText()).includes('개인 입력'));await page.locator('#intelligence').evaluate(e=>e.scrollTop=0);await page.screenshot({path:'/tmp/decision-browser/stronger-inputs-synthetic.png'});
 await terms.locator('summary').first().click();await page.fill('#di-flow','1');await page.click('#di-save-site');assert.equal(await page.locator('.di-selected .di-status-badge').getAttribute('data-status'),'WEAK');
 assert.deepEqual(privateWrites,[]);assert.deepEqual(authenticated,[]);assert.deepEqual(errors,[]);
 await browser.close();console.log('PASS: decision-first desktop/mobile, cross-family alternatives, scoped private terms/backup, owner override, stronger-input PROMISING and weak economics, dynamic legends, hover dismissal, no server writes/authentication.');
})().catch(e=>{console.error(e);process.exit(1);});
