const assert=require('node:assert/strict'),fs=require('fs'),D=require('../docs/assets/decision-intelligence.js');
const catalog=JSON.parse(fs.readFileSync('docs/data/business-workbench.json')),areas=JSON.parse(fs.readFileSync('docs/data/seoul-opportunity-map.json')).areas;
const area=areas.find(a=>a.trdar_cd==='3001492'),market={...JSON.parse(fs.readFileSync('docs/data/real-estate-context.json')).markets[0],unit:'THOUSAND_KRW_SQM_MONTH'};
const variant=id=>catalog.variants.find(v=>v.variant_id===id),evaluate=(id,extra={})=>D.evaluate({variant:variant(id),catalog,area,market,...extra}),close=(a,b)=>assert.ok(Math.abs(a-b)<1e-6,`${a} != ${b}`);
const vending=evaluate('VEND-BEVERAGE',{settings:{owner_available:true}}),b=vending.results.base;
assert.equal(vending.status,'CHECK');assert.equal(vending.confidence,'LOW','attractiveness cannot inflate confidence');
close(b.contribution_per_unit,2000*(1-.025-.02)-1000);assert.equal(b.break_even_units_month,Math.ceil(b.monthly_fixed/910));close(b.cash_required,vending.cash.base.equipment+vending.cash.base.nonrecoverable_setup+vending.cash.base.working_capital+vending.cash.base.recoverable_deposit);
close(b.capital_at_risk,b.cash_required-vending.cash.base.recoverable_deposit);assert.ok(vending.cash.low.total<vending.cash.base.total&&vending.cash.base.total<vending.cash.high.total);
close(vending.capture.rate,b.break_even_units_day/(area.day_flow/91));assert.equal(vending.capture.denominator_evidence,'PLANNING_ASSUMPTION_TEMPORAL_GRAIN');
const observed=evaluate('VEND-BEVERAGE',{settings:{daily_flow:100000,operating_days:20,volume:1000,recovery_months:24}});close(observed.max_site_with_recovery,1000*b.contribution_per_unit-b.lineage.non_site_fixed.value-b.capital_at_risk/24);assert.equal(observed.capture.denominator_evidence,'USER_INPUT');
for(const row of vending.sensitivity){close(row.conditional_monthly_surplus,row.volume*b.contribution_per_unit-b.monthly_fixed);assert.ok(row.label.includes('NOT DEMAND FORECAST'));}
assert.ok(vending.sensitivity[0].conditional_monthly_surplus<0);assert.ok(vending.sensitivity[2].conditional_monthly_surplus>0);close(vending.sensitivity[2].capital_recovery_months,b.capital_at_risk/vending.sensitivity[2].conditional_monthly_surplus);
assert.ok(vending.recovery[0].recovery_units_month>vending.recovery[1].recovery_units_month&&vending.recovery[1].recovery_units_month>vending.recovery[2].recovery_units_month);
const unfavorable=evaluate('VEND-BEVERAGE',{settings:{actual_rent:5000000,volume:300}});assert.equal(unfavorable.status,'WEAK');assert.ok(unfavorable.max_site_with_recovery<unfavorable.rent.base);assert.equal(unfavorable.rent.evidence,'USER_INPUT');
const blocked=evaluate('VEND-BEVERAGE',{blockers:['호스트 설치 금지']});assert.equal(blocked.status,'BLOCKED');assert.equal(blocked.gates.find(g=>g.id==='legal').pass,false);
const sing=evaluate('BOOTH-SING');close(sing.results.base.required_utilization,sing.results.base.break_even_units_month/(30*720));assert.ok(sing.results.base.break_even_transactions_month>0);
assert.equal(evaluate('BOOTH-SING',{settings:{actual_rent:100000000}}).status,'WEAK');
const unknown=evaluate('VEND-BEVERAGE',{overrides:{cogs:D.cell(D.range(null),'UNKNOWN',null,'견적 없음')}});assert.equal(unknown.results.base.contribution_per_unit,null);assert.equal(unknown.results.base.break_even_units_month,null);assert.equal(unknown.status,'CHECK');assert.throws(()=>D.cell(D.range(2,1,3)));
const city=D.resolveMarket(area,[market,{...market,geography_id:'not-proven',geography_type:'submarket',name:'명동'}]);assert.equal(city.geography_type,'city');assert.equal(D.resolveMarket(area,[{...market,unit:'UNKNOWN'}]),null);assert.equal(D.resolveMarket(area,[market,{...market,geography_id:'myeongdong',geography_type:'submarket'}],[{trdar_cd:area.trdar_cd,geography_id:'myeongdong',method:'EXPLICIT_PUBLISHED_CROSSWALK'}]).geography_type,'submarket');
assert.equal(vending.market_rent_baseline.method,'STATISTIC_TIMES_AREA_PLANNING_FACTOR');assert.ok(vending.market_rent_baseline.limitations.some(s=>s.includes('월 현금')));assert.equal(D.freshness('20262','2026-10-05').status,'CURRENT');assert.equal(D.freshness('20254','2026-10-05').status,'STALE');assert.equal(D.freshness('20264','2026-10-05').status,'FUTURE');
const k=[{id:'k1',name:'테스트 편의점',lat:37.56,lng:126.98,category:'편의점'},{id:'k2',name:'프린트카페',lat:37.5602,lng:126.98,category:'문서출력'}],o=[{bizesId:'o1',bizesNm:'테스트편의점',lat:37.56,lon:126.98,indsSclsNm:'편의점'},{bizesId:'o2',bizesNm:'음료자판기',lat:37.5603,lon:126.98,indsSclsNm:'자동판매'}];
const matched=D.crossMatch([...k,k[0]],o);assert.equal(matched.filter(r=>r.status==='MATCHED').length,1);assert.equal(matched.length,3);assert.equal(D.crossMatch(k,[...o,{...o[0],bizesId:'ambiguous'}]).filter(r=>r.status==='MATCHED').length,0);
assert.equal(D.classify(variant('VEND-BEVERAGE'),{indsSclsNm:'편의점'}),'SUBSTITUTE');assert.equal(D.classify(variant('VEND-BEVERAGE'),{name:'음료자판기'}),'DIRECT');assert.equal(D.classify(variant('DOCUMENT-PRINT'),{indsSclsNm:'복사/인쇄'}),'DIRECT');assert.equal(D.classify(variant('BOOTH-SING'),{name:'코인노래방'}),'DIRECT');assert.equal(D.classify(variant('BOOTH-SING'),{indsSclsNm:'게임 오락'}),'CONTEXT');
const competition=D.competition(variant('VEND-BEVERAGE'),{lat:37.56,lng:126.98},k,{stores:o,coverage:[{center:{lat:37.56,lng:126.98},radius_m:800,complete:true}],retrieved_at:'2026-10-05'},'2026-10-05');assert.equal(competition.bands[0].roles.SUBSTITUTE.unique_observed,1);assert.equal(competition.bands[0].roles.SUBSTITUTE.kakao,1);assert.equal(competition.bands[0].roles.SUBSTITUTE.official,1);assert.equal(competition.official_coverage,'COMPLETE_TARGET_CIRCLE');
const rows=Array.from({length:6},(_,i)=>({id:String(i),scope:'3001492',address:'PRIVATE',area_sqm:4,floor:'1',deposit:i===0?null:10000000,rent:[100000,110000,120000,130000,140000,1000000][i],management:null,observed_at:'2026-10-01',source_url:'https://example.com/listing/'+i}));
const imports=D.importComparables(JSON.stringify(rows)),stats=D.comparableStats(imports,{scope:'3001492',floor:'1',area_sqm:4,asOf:'2026-10-05'});assert.equal(stats.count,6);assert.equal(stats.rent.median,125000);assert.equal(stats.management.median,null);assert.deepEqual(stats.outliers,['5']);assert.equal(D.comparableStats(imports,{scope:'other',asOf:'2026-10-05'}).count,0);
const comparableRent=D.rentEnvelope({market,area_sqm:4,floor:'1',scope:'3001492',comparables:imports,asOf:'2026-10-05'});assert.equal(comparableRent.method,'PRIVATE_COMPARABLE_IQR');assert.equal(comparableRent.base,125000);assert.equal(comparableRent.actual_quoted_rent,null);
const csv='id,scope,address,area_sqm,floor,deposit,rent,management,observed_at,source_url\na,3001492,"주소, 설명",4,1,,120000,,2026-10-01,https://example.com/a';assert.equal(D.importComparables(csv)[0].address,'주소, 설명');assert.throws(()=>D.importComparables(JSON.stringify([{...rows[0],source_url:'javascript:alert(1)'}])));assert.throws(()=>D.importComparables(JSON.stringify([rows[0],rows[0]])));
const compatibility=D.buildingCompatibility(variant('BOOTH-SING'),{mainPurpsCdNm:'제2종근린생활시설'});assert.equal(compatibility.physical_fit,'PLAUSIBLE');assert.equal(compatibility.legal_fit,'NOT_VERIFIED');assert.ok(compatibility.checks.some(c=>c.item==='소방'&&c.status==='UNKNOWN'));
const override=evaluate('VEND-BEVERAGE',{settings:{owner_override:{rating:'STRONG'}}});assert.equal(override.status,'CHECK');assert.equal(override.owner_override.rating,'STRONG');
console.log('PASS: conditional cash/BE/capture/recovery/site ceilings, unknowns, explicit gates, source matching, scoped comparables, geography, freshness and building limits.');

const stress=evaluate('VEND-BEVERAGE',{settings:{volume:300},overrides:{rent:D.cell(D.range(5000000),'PLANNING_ASSUMPTION','Adverse stress','No real quote')}});assert.equal(stress.rent.base,5000000);assert.equal(stress.rent.evidence,'PLANNING_ASSUMPTION');assert.equal(stress.status,'WEAK');

// Every retained and added variant uses its declared revenue unit and yields a reviewable envelope.
for(const v of catalog.variants){const e=evaluate(v.variant_id);assert.equal(e.stack.model,v.economic_model);assert.ok(Number.isFinite(e.cash.base.total)&&e.cash.base.total>0);assert.ok(e.stack.rows.every(r=>D.CLASSES.includes(r.evidence)));if(['TIME','STORAGE'].includes(v.economic_model))assert.ok(Number.isFinite(e.results.base.required_utilization));if(['ORDER','EVENT'].includes(v.economic_model))assert.equal(e.capture.rate,null);}

const floorCell={name:market.name,asset_class:'SMALL_RETAIL',period:market.period,floor:'2층',item:'임대료',unit_label:'천원/㎡',value:30,source_id:'R_ONE:floor-fixture'};
const floorRent=D.rentEnvelope({market,area_sqm:8,floor:'2',floor_evidence:[floorCell],asOf:'2026-10-05'});assert.equal(floorRent.method,'FLOOR_STATISTIC_TIMES_AREA_PLANNING_BAND');assert.equal(floorRent.base,240000);assert.ok(floorRent.sources.includes(floorCell.source_id));
for(const mismatch of [{asset_class:'OFFICE'},{period:'20254'},{name:'다른 시장'},{unit_label:'%'},{item:'효용비율'}])assert.equal(D.rentEnvelope({market,area_sqm:8,floor:'2',floor_evidence:[{...floorCell,...mismatch}]}).method,'STATISTIC_TIMES_AREA_PLANNING_FACTOR');

assert.equal(D.rentEnvelope({market,area_sqm:4,floor:'1층'}).base,D.rentEnvelope({market,area_sqm:4,floor:'1'}).base);assert.equal(D.comparableStats(imports,{scope:'3001492',floor:'지상 1층',area_sqm:4,asOf:'2026-10-05'}).count,6);assert.equal(D.rentEnvelope({market,area_sqm:8,floor:'지상 2층',floor_evidence:[floorCell]}).base,240000);

// Review regression: facts, observability, site arrangement and planning signals
// may inform economics without automatically becoming recommendation evidence.
const point={lat:37.56,lng:126.98},asOf='2026-10-05';
const emptyCircle={stores:[],coverage:[{center:point,radius_m:800,complete:true}],retrieved_at:asOf};
const gate=(p,id)=>p.gates.find(g=>g.id===id);
const baseline=evaluate('VEND-BEVERAGE',{point,cache:emptyCircle,asOf,settings:{site_commercial_model:'FULL_LEASE',owner_available:true,daily_flow:100000}});
assert.equal(baseline.site_cost_basis,'MARKET_RENT_BASELINE');assert.equal(baseline.status,'CHECK');assert.equal(gate(baseline,'site_terms').pass,null);assert.equal(baseline.market_rent_baseline.base,market.rent_thousand_krw_per_sqm*1000*4);
const poorZero=evaluate('VEND-BEVERAGE',{point,cache:emptyCircle,asOf,settings:{owner_available:true}});
assert.equal(poorZero.competition.bands[2].roles.DIRECT.unique_observed,0);assert.equal(poorZero.competition_observability,'POOR');assert.equal(gate(poorZero,'competition').pass,null);assert.equal(poorZero.site_cost_basis,'HOST_MODEL_ESTIMATE');assert.equal(poorZero.rent.actual_quoted_rent,null);assert.equal(poorZero.status,'CHECK');
const goodZero=evaluate('DOCUMENT-PRINT',{point,cache:emptyCircle,asOf});assert.equal(goodZero.competition_observability,'GOOD');assert.equal(gate(goodZero,'competition').pass,true);
assert.equal(evaluate('BOOTH-CALL',{point,cache:emptyCircle,asOf}).competition_observability,'POOR');
const partial=evaluate('DOCUMENT-PRINT',{point,kakao:[{id:'observed',name:'문맥 업소',lat:point.lat,lng:point.lng}],kakao_retrieved_at:asOf,asOf});assert.equal(partial.competition_observability,'PARTIAL');
const stale=evaluate('DOCUMENT-PRINT',{point,cache:{...emptyCircle,retrieved_at:'2025-01-01'},asOf});assert.equal(stale.competition_observability,'UNKNOWN');assert.equal(gate(stale,'competition').pass,null);
const plannedLow=evaluate('DOCUMENT-PRINT',{point,cache:emptyCircle,asOf,area:{...area,weekday_flow:100000},settings:{owner_available:true,actual_rent:100000,quarter_days:1}}),plannedHigh=evaluate('DOCUMENT-PRINT',{point,cache:emptyCircle,asOf,area:{...area,weekday_flow:100000},settings:{owner_available:true,actual_rent:100000,quarter_days:366}});
assert.notEqual(plannedLow.capture.rate,plannedHigh.capture.rate);assert.equal(plannedLow.status,plannedHigh.status);assert.equal(plannedLow.status,'CHECK');assert.equal(gate(plannedHigh,'capture').pass,null);assert.equal(plannedHigh.capture.gate_eligible,false);
const strong=evaluate('DOCUMENT-PRINT',{point,cache:emptyCircle,asOf,settings:{site_commercial_model:'FULL_LEASE',owner_available:true,actual_rent:100000,daily_flow:100000}});
assert.equal(strong.site_cost_basis,'ACTUAL_SITE_TERMS');assert.equal(strong.rent.base,100000);assert.equal(strong.market_rent_baseline.base,baseline.market_rent_baseline.base);assert.equal(strong.capture.denominator_evidence,'USER_INPUT');assert.equal(gate(strong,'capture').pass,true);assert.equal(strong.status,'PROMISING');assert.equal(strong.confidence,'LOW');
const excessive=evaluate('DOCUMENT-PRINT',{point,cache:emptyCircle,asOf,settings:{actual_rent:100000,owner_available:true,daily_flow:1}});assert.equal(excessive.status,'WEAK');assert.equal(gate(excessive,'capture').pass,false);
const assumedHost=evaluate('DOCUMENT-PRINT',{point,cache:emptyCircle,asOf,settings:{owner_available:true,daily_flow:100000}});assert.equal(assumedHost.site_cost_basis,'HOST_MODEL_ESTIMATE');assert.equal(assumedHost.status,'CHECK');
const quoteWins=evaluate('DOCUMENT-PRINT',{settings:{actual_rent:200000},overrides:{rent:D.cell(D.range(9999999),'PLANNING_ASSUMPTION')}});assert.equal(quoteWins.rent.base,200000);assert.equal(quoteWins.site_cost_basis,'ACTUAL_SITE_TERMS');
const leaseComps=evaluate('DOCUMENT-PRINT',{point,cache:emptyCircle,asOf,comparables:imports,settings:{site_commercial_model:'FULL_LEASE',owner_available:true,daily_flow:100000}});assert.equal(leaseComps.site_cost_basis,'PRIVATE_COMPARABLES');assert.equal(leaseComps.status,'PROMISING');
const hostComps=evaluate('VEND-BEVERAGE',{comparables:imports,asOf});assert.equal(hostComps.site_cost_basis,'HOST_MODEL_ESTIMATE');assert.notEqual(hostComps.rent.base,125000);
const share=evaluate('VEND-BEVERAGE',{settings:{site_commercial_model:'HOST_REVENUE_SHARE'}});assert.equal(share.rent.base,0);assert.equal(share.site_cost_basis,'HOST_MODEL_ESTIMATE');assert.equal(share.stack.rows.find(r=>r.key==='host_share').base,.2);assert.notEqual(share.results.base.contribution_per_unit,vending.results.base.contribution_per_unit);
const incompleteShare=evaluate('VEND-BEVERAGE',{settings:{site_commercial_model:'HOST_REVENUE_SHARE',actual_rent:0}});assert.equal(incompleteShare.site_cost_basis,'HOST_MODEL_ESTIMATE');
const privateShare=evaluate('VEND-BEVERAGE',{settings:{site_commercial_model:'HOST_REVENUE_SHARE',actual_rent:0},overrides:{host_share:D.cell(D.range(.1),'USER_INPUT'),minimum_host:D.cell(D.range(0),'USER_INPUT')}});assert.equal(privateShare.site_cost_basis,'ACTUAL_SITE_TERMS');
const metadata={value:100000,evidence:'PUBLIC_SOURCE',temporal_grain:'DAILY',geography_id:area.trdar_cd,source_id:'TEST_ONLY:daily-metadata',opportunity_unit:'TRANSACTION'};
const verified=evaluate('DOCUMENT-PRINT',{point,cache:emptyCircle,asOf,verified_daily_flow:metadata,settings:{actual_rent:100000,owner_available:true}});assert.equal(verified.status,'PROMISING');assert.equal(verified.capture.denominator_evidence,'PUBLIC_SOURCE');
assert.equal(evaluate('DOCUMENT-PRINT',{verified_daily_flow:{...metadata,geography_id:'another-area'}}).capture.gate_eligible,false);
const all=catalog.variants.map(v=>evaluate(v.variant_id,{point,cache:emptyCircle,asOf})),location=D.locationPlays(all);
assert.equal(location.length,3);assert.ok(new Set(location.map(p=>p.parent_candidate_id)).size>=2);assert.ok(location.every(p=>D.LOCATION_FAMILIES.includes(p.parent_candidate_id)));assert.ok(!location.some(p=>['MRO-BASKET','EVENT-PHOTO'].includes(p.variant_id)));
assert.deepEqual(D.locationPlays([...all].reverse()).map(p=>p.variant_id),location.map(p=>p.variant_id),'stable documented tie breakers');
assert.equal(D.topPlays(all,'VEND-BEVERAGE')[0].variant_id,'VEND-BEVERAGE');assert.equal(D.topPlays(all,'VEND-BEVERAGE').length,4);
assert.equal(evaluate('DOCUMENT-PRINT',{point,cache:emptyCircle,asOf,settings:{owner_available:false,actual_rent:100000,daily_flow:100000}}).status,'WEAK');
const negativeKnown=evaluate('VEND-BEVERAGE',{market:null,settings:{site_commercial_model:'FULL_LEASE'},overrides:{price:D.cell(D.range(0))}});assert.equal(negativeKnown.status,'WEAK','known negative contribution survives other missing costs');
const crowded={...emptyCircle,stores:Array.from({length:12},(_,i)=>({bizesId:String(i),bizesNm:'음료자판기'+i,lat:point.lat,lon:point.lng}))};const observedMachines=evaluate('VEND-BEVERAGE',{point,cache:crowded,asOf});assert.equal(observedMachines.status,'WEAK','poor absence observability does not erase reliable positive competitor observations');
assert.equal(unfavorable.status,'WEAK');assert.equal(blocked.status,'BLOCKED');
console.log('PASS: reviewed site bases/models, source capability and zero observations, temporal-grain neutrality, stronger PROMISING/negative gates, cross-family ranking and selected scenario isolation.');

const baselineWithGoodEvidence=evaluate('DOCUMENT-PRINT',{point,cache:emptyCircle,asOf,settings:{site_commercial_model:'FULL_LEASE',owner_available:true,daily_flow:100000}});assert.equal(baselineWithGoodEvidence.competition_observability,'GOOD');assert.equal(gate(baselineWithGoodEvidence,'capture').pass,true);assert.equal(baselineWithGoodEvidence.site_cost_basis,'MARKET_RENT_BASELINE');assert.equal(baselineWithGoodEvidence.status,'CHECK','baseline alone cannot promote even when all other decision evidence passes');

assert.ok(plannedLow.capture.rate<.01&&plannedHigh.capture.rate>.01,'opposite sides of capture threshold remain informational');
const stalePositive=evaluate('DOCUMENT-PRINT',{point,cache:emptyCircle,asOf,kakao_retrieved_at:'2025-01-01',kakao:Array.from({length:12},(_,i)=>({id:'stale'+i,name:'프린트카페'+i,lat:point.lat,lng:point.lng}))});assert.equal(stalePositive.competition.bands[2].roles.DIRECT.unique_observed,12);assert.equal(stalePositive.competition.reliable_direct_count,0);assert.equal(gate(stalePositive,'competition').pass,true,'stale sample positives do not become recent high-competition evidence');
