const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('fs'),path=require('path');
const base=process.env.GIS_TEST_URL||'http://127.0.0.1:8765/SideEconomyLab/';
fs.mkdirSync('/tmp/decision-browser',{recursive:true});
(async()=>{
 const browser=await chromium.launch({headless:true,...(process.env.WORKBENCH_CHROMIUM?{executablePath:process.env.WORKBENCH_CHROMIUM}:{})});
 const page=await browser.newPage({viewport:{width:1600,height:1000}}),errors=[],privateWrites=[],authenticated=[];
 page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(r.method()!=='GET')privateWrites.push(r.method());if(/apis\.data\.go\.kr|reb\.or\.kr/.test(r.url()))authenticated.push('server-only-domain-request');});
 for(const [url,file] of [['https://unpkg.com/leaflet@1.9.4/dist/leaflet.js','leaflet/dist/leaflet.js'],['https://unpkg.com/leaflet@1.9.4/dist/leaflet.css','leaflet/dist/leaflet.css'],['https://cdnjs.cloudflare.com/ajax/libs/proj4js/2.11.0/proj4.js','proj4/dist/proj4.js']])await page.route(url,r=>r.fulfill({path:require.resolve(file)}));
 await page.route('https://*.tile.openstreetmap.org/**',r=>r.abort());
 await page.goto(base);await page.waitForFunction(()=>document.querySelectorAll('.di-play').length===3);
 assert.ok(await page.locator('#di-variant').isVisible());assert.equal(await page.locator('#filter-panel').evaluate(e=>e.open),false);assert.ok((await page.locator('#decision-panel').innerText()).startsWith('DECISION SNAPSHOT'));
 const rankBox=await page.locator('.top-item').nth(4).boundingBox();assert.ok(rankBox.y+rankBox.height<1000,'ranked locations visible without opening long filters');
 const mapBox=await page.locator('#map').boundingBox();assert.ok(mapBox.width>800);
 await page.selectOption('#candidate','vending');await page.selectOption('#di-variant','VEND-BEVERAGE');await page.waitForFunction(()=>document.querySelector('.di-play')?.dataset.variant==='VEND-BEVERAGE');
 assert.equal(await page.locator('#di-variant option').count(),4,'source-backed snack and amenity variants');
 const overview=await page.locator('.di-play').first().innerText();for(const term of ['초기 현금','월 공간비','손익분기','필요 포획률','LOW','다음 하나'])assert.ok(overview.includes(term));
 await page.locator('#decision-panel').evaluate(e=>e.parentElement.scrollTop=0);await page.screenshot({path:'/tmp/decision-browser/myeongdong-vending.png'});
 const details=page.locator('.di-detail').filter({hasText:'사이트 비용 추정 · 실제 견적과 구별'});await details.locator('summary').first().click();await page.fill('#di-rent','5000000');await page.click('#di-save-site');await page.fill('#di-volume','300');await page.click('#di-save-volume');assert.ok((await page.locator('.di-play').first().innerText()).includes('WEAK'));assert.ok((await page.locator('#decision-panel').innerText()).includes('ECONOMICS FAILS AT THIS VOLUME'));
 await page.screenshot({path:'/tmp/decision-browser/unfavorable-site.png'});
 await details.locator('summary').first().click();await page.fill('#di-blockers','PRIVATE host prohibits installation');await page.click('#di-save-site');assert.equal(await page.locator('.di-play .di-status-badge').first().innerText(),'BLOCKED');await details.locator('summary').first().click();await page.fill('#di-blockers','');await page.click('#di-save-site');assert.equal(await page.locator('.di-play .di-status-badge').first().innerText(),'WEAK');
 // Hover-first: mouse leave, Escape and map background dismiss, including mobile tap.
 await page.locator('#intelligence').evaluate(e=>e.scrollTop=0);await page.evaluate(()=>state.adapter.focus(toLatLng(state.selectedArea)));await page.waitForTimeout(100);await page.evaluate(()=>{for(const el of document.querySelectorAll('.poi-marker')){const r=el.getBoundingClientRect(),hit=document.elementFromPoint(r.x+r.width/2,r.y+r.height/2);if(hit===el){el.dataset.testExposed='true';break;}}});const marker=page.locator('[data-test-exposed=true]');await marker.hover();await page.locator('.leaflet-tooltip').waitFor();await page.mouse.move(mapBox.x+5,mapBox.y+5);await page.waitForFunction(()=>document.querySelectorAll('.leaflet-tooltip').length===0);assert.equal(await page.locator('.leaflet-tooltip').count(),0);await marker.click();await page.locator('.leaflet-tooltip').waitFor();await page.keyboard.press('Escape');await page.waitForFunction(()=>document.querySelectorAll('.leaflet-tooltip').length===0);assert.equal(await page.locator('.leaflet-tooltip').count(),0);
 await page.locator('#filter-panel').evaluate(e=>e.open=true);for(const mode of ['supply','quadrant','demand']){await page.selectOption('#map-mode',mode);const legend=await page.locator('#map-legend').innerText();for(const text of ['직접 경쟁형','대체형','문맥','개인/실제 후보지','선택 상권'])assert.ok(legend.includes(text));}
 // Explicit map creation and browser-only quick terms.
 await page.click('#di-map-create');await page.mouse.click(mapBox.x+mapBox.width*.45,mapBox.y+mapBox.height*.4);await page.waitForFunction(()=>document.querySelector('#di-location').value!=='');
 assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('SideEconomyLab.business-workbench.v1')).sites.length),1);assert.equal(await page.locator('.site-marker').count(),1);
 await page.locator('.di-detail').filter({hasText:'사이트 비용 추정 · 실제 견적과 구별'}).locator('summary').first().click();
 for(const [id,value] of [['di-area','6'],['di-floor','2'],['di-rent','900000'],['di-quick-deposit','9000000'],['di-quick-management','100000'],['di-quick-key_money','0'],['di-quick-host_share','.1']])await page.fill('#'+id,value);
 await page.click('#di-save-site');assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('SideEconomyLab.business-workbench.v1')).sites[0].rent.value),900000);
 await page.reload();await page.waitForFunction(()=>document.querySelectorAll('.di-play').length===3);assert.equal(await page.locator('#di-location option').count(),2);
 // Complete private backup/import and owner override preserve public status.
 await page.selectOption('#candidate','vending');await page.selectOption('#di-variant','VEND-BEVERAGE');await page.selectOption('#di-location',{index:1});
 await page.locator('.di-detail').filter({hasText:'소유자 판단 · 관측 결과 · 개인 백업'}).locator('summary').first().click();await page.selectOption('#di-judgment','STRONG');await page.fill('#di-reason','PRIVATE judgement');await page.fill('#di-change','PRIVATE evidence');const before=await page.locator('.di-play .di-status-badge').first().innerText();await page.click('#di-save-judgment');assert.equal(await page.locator('.di-play .di-status-badge').first().innerText(),before);assert.ok((await page.locator('.di-play').first().innerText()).includes('OWNER OVERRIDE STRONG'));
 await page.locator('.di-detail').filter({hasText:'소유자 판단 · 관측 결과 · 개인 백업'}).locator('summary').first().click();const downloadEvent=page.waitForEvent('download');await page.click('#di-export');const file=await (await downloadEvent).path();const backup=JSON.parse(fs.readFileSync(file));assert.equal(backup.workbench.sites[0].rent.value,900000);assert.ok(Object.keys(backup.decision.envelopes).length>0);
 await page.locator('#di-import').setInputFiles({name:'backup.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(backup))});await page.waitForFunction(()=>document.querySelector('#di-status').textContent.includes('복원 완료'));
 // Invalid private restore must preserve both keys.
 const saved=await page.evaluate(()=>[localStorage.getItem('SideEconomyLab.decision-intelligence.v1'),localStorage.getItem('SideEconomyLab.business-workbench.v1')]);await page.locator('.di-detail').filter({hasText:'소유자 판단 · 관측 결과 · 개인 백업'}).locator('summary').first().click();await page.locator('#di-import').setInputFiles({name:'invalid.json',mimeType:'application/json',buffer:Buffer.from('{"schema_version":999}')});await page.waitForFunction(()=>document.querySelector('#di-status').textContent.includes('복원 실패'));assert.deepEqual(await page.evaluate(()=>[localStorage.getItem('SideEconomyLab.decision-intelligence.v1'),localStorage.getItem('SideEconomyLab.business-workbench.v1')]),saved);
 await page.setViewportSize({width:390,height:844});await page.reload();await page.waitForFunction(()=>document.querySelectorAll('.di-play').length===3);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.ok(await page.locator('#di-variant').isVisible());await page.click('.mobile-tabs [data-sheet="decision"]');assert.ok(await page.locator('#decision-panel').isVisible());await page.screenshot({path:'/tmp/decision-browser/mobile-decision.png'});
 await page.click('#intelligence [data-sheet="close"]');await page.click('.mobile-tabs [data-sheet="filters"]');await page.locator('#filter-panel').evaluate(e=>e.open=true);await page.selectOption('#map-mode','quadrant');assert.ok((await page.locator('#map-legend').innerText()).includes('A 고수요'));await page.click('#navigator [data-sheet="close"]');
 assert.deepEqual(privateWrites,[]);assert.deepEqual(authenticated,[]);assert.deepEqual(errors,[]);
 await browser.close();console.log('PASS: decision-first desktop/mobile, private point/terms/backup, owner override, weak economics, dynamic legends, hover dismissal, no server writes/authentication.');
})().catch(e=>{console.error(e);process.exit(1);});
