"""Public catalog provenance, isolation and unchanged research/data contracts."""
import hashlib
import json
from datetime import date
from pathlib import Path
import unittest

ROOT = Path(__file__).resolve().parents[1]


class WorkbenchCatalogTests(unittest.TestCase):
    def setUp(self):
        self.catalog = json.loads((ROOT / 'docs/data/business-workbench.json').read_text())

    def test_variant_parent_and_source_references_and_primitives(self):
        registry = json.loads((ROOT / 'docs/data/candidate-registry.json').read_text())
        parents = {c['id'] for c in registry['candidates']}
        variants = self.catalog['variants']
        self.assertEqual(len({v['variant_id'] for v in variants}), len(variants))
        sources = {s['source_id'] for s in self.catalog['sources']}
        self.assertEqual({v['economic_model'] for v in variants}, {'UNIT_SALE', 'TRANSACTION', 'TIME', 'STORAGE', 'ORDER', 'EVENT'})
        for v in variants:
            self.assertIn(v['parent_candidate_id'], parents)
            self.assertLessEqual(set(v['source_ids']), sources)
            for key in ['customer_job', 'payer', 'revenue_unit', 'equipment_service_class', 'typical_host_archetype', 'required_site_attributes', 'capex_components', 'opex_components', 'revenue_variables', 'operational_constraints', 'legal_regulatory_unknowns']:
                self.assertTrue(v[key], (v['variant_id'], key))
        self.assertFalse(any('gacha' in v['variant_id'].lower() for v in variants))

    def test_catalog_nulls_prices_specs_and_device_footprint(self):
        variants = {v['variant_id'] for v in self.catalog['variants']}
        rows = self.catalog['configurations']
        self.assertEqual(len({c['configuration_id'] for c in rows}), len(rows))
        for c in rows:
            self.assertLessEqual(set(c['variant_ids']), variants)
            date.fromisoformat(c['observed_at'])
            self.assertIsNone(c['resale_recovery_krw'])
            self.assertIsNone(c['software_monthly_fee_krw'])
            if c['dimensions_mm']:
                w, _, d = c['dimensions_mm']
                self.assertAlmostEqual(c['footprint_sqm'], w * d / 1e6)
            else:
                self.assertIsNone(c['footprint_sqm'])
        by_id = {c['configuration_id']: c for c in rows}
        self.assertEqual(by_id['C-SM06-STATION']['asking_price_krw'], 5500000)
        self.assertEqual(by_id['C-SM06-STATION']['vat_treatment'], 'INCLUDED')
        self.assertEqual(by_id['C-CHIKI-EVENT']['vat_treatment'], 'EXCLUDED')
        self.assertIsNone(by_id['C-BOOTH-CUSTOM']['asking_price_krw'])
        self.assertEqual(by_id['C-VEND-USED']['asking_price_krw'], 2500000)

    def test_public_source_capture_links_and_dates_without_authentication(self):
        for s in self.catalog['sources']:
            self.assertTrue(s['url'].startswith('https://'))
            self.assertNotIn('serviceKey', s['url'])
            date.fromisoformat(s['observed_at'])
            path = (ROOT / s['repository_reference']).resolve()
            self.assertTrue(path.is_relative_to(ROOT))
            self.assertTrue(path.is_file())
            if s['access_status'] == 'HTTP_200_PUBLIC_CONTENT':
                captured = json.loads(path.read_text())
                self.assertEqual(captured['response_sha256'], s['response_sha256'])
                self.assertEqual(captured['excerpt'], s['excerpt'])
                self.assertEqual(len(s['response_sha256']), 64)
        self.assertFalse(self.catalog['additional_source']['required_secret_added'])

    def test_pr13_semantics_raw_gis_and_mutation_chain_remain_identical(self):
        pins = json.loads((ROOT / 'research/workbench-preservation-v1.json').read_text())
        for name, expected in pins['unchanged_files'].items():
            self.assertEqual(hashlib.sha256((ROOT / name).read_bytes()).hexdigest(), expected, name)
        # Scheduled refreshes may change generated bytes; their exact dependencies must still validate.
        import sys
        sys.path.insert(0, str(ROOT / 'pipeline'))
        from gis_refresh import validate_bundle
        validate_bundle(ROOT)
        portfolio = json.loads((ROOT / 'docs/data/candidate-validation-portfolio.json').read_text())
        semantic = {k: v for k, v in portfolio.items() if k != 'integrity_baseline'}
        actual = hashlib.sha256(json.dumps(semantic, sort_keys=True, ensure_ascii=False).encode()).hexdigest()
        self.assertEqual(actual, pins['portfolio_semantics_sha256'])
        self.assertFalse(portfolio['pilot_authorized'])
        self.assertEqual(json.loads((ROOT / 'docs/data/site-observations.json').read_text())['sites'], [])

    def test_public_catalog_contains_no_private_workspace_or_site_samples(self):
        self.assertNotIn('sites', self.catalog)
        self.assertNotIn('scenarios', self.catalog)
        schema = json.loads((ROOT / 'docs/data/business-workbench.schema.json').read_text())
        self.assertFalse(schema['additionalProperties'])
        scripts = (ROOT / 'docs/assets/workbench.js').read_text()
        self.assertNotIn('method:', scripts)
        self.assertNotIn('sendBeacon', scripts)
        self.assertNotIn('XMLHttpRequest', scripts)
        self.assertIn('PRIVATE JSON', scripts)


if __name__ == '__main__':
    unittest.main()
