const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const E=require('../docs/assets/economics.js'),W=require('../docs/assets/business-workspace.js');
const catalog=JSON.parse(fs.readFileSync(path.join(__dirname,'../docs/data/business-workbench.json')));
let count=0;function test(name,fn){fn();count++;console.log('PASS '+name);}
function inputs(model){return Object.fromEntries(E.fields(model).map(k=>[k,E.input(0,'ASSUMPTION')]));}
function complete(model){const x=inputs(model);for(const k of ['operating_days','recovery_months','session_minutes','operating_minutes_per_day','capacity','storage_capacity'])if(k in x)x[k]=E.input(({operating_days:30,recovery_months:12,session_minutes:20,operating_minutes_per_day:600,capacity:1,storage_capacity:20})[k],'ASSUMPTION');x.non_site_fixed=E.input(300000);x.rent=E.input(600000);x.management=E.input(100000);x.acquisition=E.input(6000000);x.deposit=E.input(2000000);x.expected_monthly_units=E.input(2000,'ASSUMPTION');return x;}
test('six primitives use their own revenue units and exact variable costs',()=>{
 for(const [model,m] of Object.entries(E.MODELS)){const x=complete(model);x[m.price]=E.input(2000);for(const k of m.costs)x[k]=E.input(100);const r=E.solve(model,x);assert.equal(r.contribution_per_unit,2000-m.costs.length*100);assert.equal(r.monthly_fixed,1000000);assert.equal(r.break_even_units_month,Math.ceil(1000000/r.contribution_per_unit));assert.equal(r.cash_required,8000000);assert.equal(r.capital_at_risk,6000000);}
});
test('reverse break-even, max rent, host ceiling and horizon are analytically correct',()=>{const x=complete('UNIT_SALE');x.unit_price=E.input(2000);x.cogs_per_unit=E.input(800);x.fulfillment_per_unit=E.input(100);x.payment_rate=E.input(.03);x.host_share=E.input(.1);const r=E.solve('UNIT_SALE',x);assert.equal(r.contribution_per_unit,840);assert.equal(r.break_even_units_month,1191);assert.equal(r.break_even_units_day,39.7);assert.equal(r.max_site_cost,1380000);assert.equal(r.max_rent,1280000);assert.equal(r.max_host_share,.27);assert.equal(r.recovery_units_month,1786);assert.equal(r.conditional_monthly_surplus,680000);assert.equal(r.capital_recovery_months,6000000/680000);});
test('unknown is never zero; absent volume never yields profit',()=>{const x=complete('TRANSACTION');x.service_price=E.input(1000);x.consumables_per_transaction=E.input(null);x.expected_monthly_units=E.input();let r=E.solve('TRANSACTION',x);assert.equal(r.contribution_per_unit,null);assert.equal(r.break_even_units_month,null);assert.equal(r.conditional_monthly_surplus,null);x.consumables_per_transaction=E.input(300);r=E.solve('TRANSACTION',x);assert.equal(r.contribution_per_unit,700);assert.equal(r.max_rent,null);assert.equal(r.capital_recovery_months,null);x.management=E.input(null);assert.equal(E.solve('TRANSACTION',x).monthly_fixed,null);});
test('negative contribution and impossible rent/share do not become zero or infinity',()=>{const x=complete('UNIT_SALE');x.unit_price=E.input(100);x.cogs_per_unit=E.input(200);let r=E.solve('UNIT_SALE',x);assert.equal(r.status,'NON_POSITIVE_CONTRIBUTION');assert.equal(r.break_even_units_month,null);assert.ok(r.max_rent<0);assert.ok(r.max_host_share<0);assert.equal(r.capital_recovery_months,null);});
test('time occupancy and storage capacity limits are explicit',()=>{const x=complete('TIME');x.price_per_minute=E.input(20);x.variable_cost_per_minute=E.input(5);x.session_minutes=E.input(20);let r=E.solve('TIME',x);assert.equal(r.available_units_month,18000);assert.equal(r.break_even_units_month,66667);assert.equal(r.break_even_transactions_month,3334);assert.equal(r.required_utilization,66667/18000);assert.equal(r.recovery_transactions_month,5000);assert.equal(r.recovery_utilization,100000/18000);assert.equal(r.status,'CAPACITY_EXCEEDED');const s=complete('STORAGE');s.price_per_bag_day=E.input(5100);s.cost_per_bag_day=E.input(2000);r=E.solve('STORAGE',s);assert.equal(r.available_units_month,600);assert.equal(r.required_utilization,323/600);});
test('invalid rates, coercions, evidence labels and sources are rejected',()=>{const x=complete('ORDER');for(const bad of [NaN,Infinity,-1,'100',true])assert.throws(()=>E.solve('ORDER',{...x,basket_revenue:E.input(bad)}));assert.throws(()=>E.solve('ORDER',{...x,host_share:E.input(1.1)}));assert.throws(()=>E.solve('ORDER',{...x,basket_revenue:E.input(100,'SOURCED')}));assert.throws(()=>E.solve('ORDER',{...x,operating_days:E.input(32)}));assert.throws(()=>E.solve('TIME',{...complete('TIME'),capacity:E.input(.5)}));assert.throws(()=>E.solve('ORDER',{...x,basket_revenue:E.input(1e308),expected_monthly_units:E.input(1e308)}),/finite range/);});
test('source/user/assumption lineage stays separate from derived results',()=>{const x=complete('EVENT');x.event_price=E.input(1200000,'USER_INPUT');x.supplier_per_event=E.input(1000000,'SOURCED','specific dated net quote (synthetic test)');x.delivery_per_event=E.input(50000,'ASSUMPTION');const r=E.solve('EVENT',x);assert.equal(r.kind,'DERIVED');assert.equal(r.lineage.supplier_per_event.kind,'SOURCED');assert.equal(r.lineage.delivery_per_event.kind,'ASSUMPTION');assert.equal(r.contribution_per_unit,150000);});
test('sensitivity is a named assumption and never mutates original inputs',()=>{const x=complete('UNIT_SALE');x.unit_price=E.input(1000);x.cogs_per_unit=E.input(500);x.expected_monthly_units=E.input();const before=JSON.stringify(x),r=E.sensitivity('UNIT_SALE',x);assert.equal(JSON.stringify(x),before);assert.equal(r.volume[0].lineage.expected_monthly_units.kind,'ASSUMPTION');assert.equal(r.volume[0].conditional_monthly_surplus,-850000);assert.equal(r.host[3].contribution_per_unit,200);assert.equal(r.host[3].conditional_monthly_surplus,null);});
const v=catalog.variants.find(v=>v.variant_id==='VEND-BEVERAGE'),s=W.site({name:'Synthetic private QA site',lat:37.56,lng:126.98}),scenario=W.scenario(v,s.site_id,'C-VEND-SLIM');const raw={schema_version:1,sites:[s],scenarios:[scenario]};
test('private store, export/import and cloning preserve identity without sharing mutable inputs',()=>{const store=new Map(),storage={getItem:k=>store.has(k)?store.get(k):null,setItem:(k,v)=>store.set(k,v)};assert.deepEqual(W.load(storage,catalog),W.empty());W.save(storage,raw,catalog);assert.deepEqual(W.load(storage,catalog),raw);assert.deepEqual(W.importJSON(W.exportJSON(raw,catalog),catalog),raw);const cloned=W.cloneScenario(scenario);assert.notEqual(cloned.scenario_id,scenario.scenario_id);cloned.inputs.unit_price.value=1000;assert.equal(scenario.inputs.unit_price.value,null);assert.equal(cloned.site_id,s.site_id);s.rent=E.input(123456);assert.equal(W.inputsFor(scenario,s).rent.value,123456);s.rent=E.input();});
test('variant/config/model isolation, malformed imports and private data sizes fail safely',()=>{
 for(const change of [r=>r.scenarios[0].variant_id='VEND-COFFEE',r=>r.scenarios[0].site_id='missing',r=>r.scenarios[0].inputs.service_price=E.input(1000),r=>r.sites[0].evidence_status='HOST_QUOTE',r=>r.sites[0].lat='37.5',r=>r.sites[0].rent=E.input(-1),r=>r.scenarios[0].judgment.confidence=101,r=>r.sites[0].notes='x'.repeat(4001),r=>r.sites[0].observed_at='2026-02-30']){const copy=W.copy(raw);change(copy);assert.throws(()=>W.validate(copy,catalog));}
 assert.throws(()=>W.importJSON('{"__proto__": {},"schema_version":1,"sites":[],"scenarios":[]}',catalog));assert.throws(()=>W.importJSON('x'.repeat(2000001),catalog));
 const large={schema_version:1,sites:Array.from({length:100},(_,i)=>({...W.site(),site_id:'size-'+i,name:'가'.repeat(4000),notes:'나'.repeat(4000)})),scenarios:[]};assert.throws(()=>W.exportJSON(large,catalog),/2MB/);assert.throws(()=>W.importJSON(JSON.stringify(large),catalog),/too large/);
 const store={setItem:()=>{throw new Error('QuotaExceeded');}};assert.throws(()=>W.save(store,raw,catalog));
});
test('variant competition excludes generic convenience stores/coworking from direct supply',()=>{const convenience={name:'CU',category:'편의점'},office={name:'패스트파이브 공유오피스',category:'공유오피스'},coffee=catalog.variants.find(v=>v.variant_id==='VEND-COFFEE'),call=catalog.variants.find(v=>v.variant_id==='BOOTH-CALL'),print=catalog.variants.find(v=>v.variant_id==='DOCUMENT-PRINT');assert.equal(W.role(v,convenience),'SUBSTITUTE');assert.equal(W.role(coffee,convenience),'SUBSTITUTE');assert.equal(W.role(call,office),'SUBSTITUTE');assert.equal(W.role(print,convenience),'CONTEXT');assert.equal(W.role(v,{name:'명동 음료자판기'}),'DIRECT');assert.equal(W.role(coffee,{name:'명동 음료자판기'}),'CONTEXT');});
test('private-site radii use coordinates, deduplicate IDs, retain incomplete coverage and unknown',()=>{
 const p={id:'qa',name:'음료자판기',category:'음료자판기',lat:s.lat+.0005,lng:s.lng,distance_m:700};
 const layer={radius_m:800,candidates:{a:{areas:[{lat:s.lat,lng:s.lng,pois:[p],query_stats:[{truncated:true}]}]},b:{areas:[{lat:s.lat,lng:s.lng,pois:[p],query_stats:[]}]}}};
 let c=W.competition(v,s,layer);assert.equal(c.bands[0].counts.DIRECT,1);assert.ok(c.nearest[0].distance_m<60);assert.equal(c.bands[0].coverage,'PARTIAL_OR_CAPPED');assert.equal(c.nearest.length,1);
 c=W.competition(v,{lat:null,lng:null},layer);assert.equal(c.status,'UNKNOWN');assert.equal(c.bands.length,0);c=W.competition(v,{lat:38,lng:127},layer);assert.equal(c.bands[0].counts.DIRECT,null);
});
test('price freshness ages without rewriting observation or inventing prices',()=>{const row=catalog.configurations.find(c=>c.configuration_id==='C-SM06-STATION');assert.equal(W.freshness(row,'2026-10-05'),'CURRENT_OBSERVATION');assert.equal(W.freshness(row,'2026-11-06'),'STALE');assert.equal(row.observed_at,'2026-10-05');assert.equal(catalog.configurations.find(c=>c.configuration_id==='C-LOCKER-QUOTE').asking_price_krw,null);});
console.log(`PASS: ${count} economics/private-workspace/competition regression groups`);
